---
- name: amazon-linux-extrasでPHP関連モジュールをインストール
  shell: "amazon-linux-extras enable php7.3"
  changed_when: False

- name: php-fpmと関連モジュールをインストール
  yum:
    name: "{{ item }}"
    enablerepo: "amzn2extra-php7.3"
  with_items:
    - php-fpm
    - php-devel
    - php-enchant
    - php-mbstring
    - php-process
    - php-xml
    - php-gd
    - "{{ php_fpm_additional_packages }}"
  notify:
    - PHP-FPMを再起動

- name: PHP-FPMの起動
  service:
    name: php-fpm
    state: started
    enabled: true
