- name: PlaybookTestRun
  hosts: all
  become: true
  tasks:
    - name: libselinux-python install
      yum:
        name: ['libselinux-python', 'policycoreutils-python']
    - name: Disable SElinux
      selinux:
        policy: targeted
        state: permissive
